# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Eric Lesiuta
"""`agent6 completions`: install (or print) shell tab-completion.

The argcomplete docs' `eval "$(register-python-argcomplete agent6)"` needs
that register script on PATH, which a uv-tool install does not guarantee. This
command is self-contained: `argcomplete.shellcode()` emits the equivalent
registration, and the default action INSTALLS it. For bash/zsh the script is
written under the agent6 config dir and one marker-guarded `source` line is
appended to the shell's rc file (idempotent: rerunning refreshes the script and
never duplicates the block). Fish gets a file in its native completions dir --
no rc edit, and fish picks it up automatically.

Xonsh is not an argcomplete target, so it gets a small generated completer
instead: argcomplete speaks a shell-agnostic protocol (env vars in, candidates
out on a side channel), and the completer drives it directly, so it stays
correct as agent6's arguments change without agent6 depending on xonsh. It
lands in the xonsh `rc.d` auto-load dir, so like fish it needs no rc edit.

The shell is detected by walking up the process tree to the nearest known
shell (a fish started from bash leaves `$SHELL=bash`), falling back to
`$SHELL`; pass `bash`, `zsh`, `fish`, or `xonsh` explicitly when
both are wrong.

A child process cannot restart the shell that launched it, so instead of
pretending to, the bash/zsh install ends by printing exactly what to run
(`source <rc>` or `exec $SHELL`) to activate the completions in the
current session.
"""

from __future__ import annotations

import os
import shlex
import sys
from pathlib import Path

from argcomplete.shell_integration import shellcode

from agent6.errors import read_operator_file
from agent6.paths import global_config_dir
from agent6.ui.cli._common import error

SHELLS = ("bash", "zsh", "fish", "xonsh")
_MARK_BEGIN = "# >>> agent6 completions >>>"
_MARK_END = "# <<< agent6 completions <<<"
_PROC = Path("/proc")  # patched in tests

# Xonsh completer. argcomplete has no xonsh backend, so this drives the
# argcomplete protocol itself: set the request in the environment, let agent6
# write its candidates to a side file (_ARGCOMPLETE_STDOUT_FILENAME), and hand
# each "value<TAB>description" line to xonsh. Registered ahead of the default
# completer so it wins for the agent6 command; a no-op for every other command.
_XONSH_SCRIPT = """\
# agent6 tab-completion for xonsh, generated by `agent6 completions xonsh`.
# It asks the agent6 on PATH for candidates at completion time (the
# argcomplete protocol: request in env vars, answer in a side file), so it
# needs no regeneration when agent6's arguments change.
import os
import shlex
import subprocess
import tempfile

from xonsh.built_ins import XSH
from xonsh.completers import completer
from xonsh.completers.tools import (
    RichCompletion,
    contextual_command_completer,
)


@contextual_command_completer
def _agent6_completer(context):
    if not context.args or os.path.basename(context.args[0].value) != "agent6":
        return None
    line = context.text_before_cursor
    handle = tempfile.NamedTemporaryFile(delete=False)
    handle.close()
    env = {
        **XSH.env.detype(),
        "_ARGCOMPLETE": "1",
        "_ARGCOMPLETE_IFS": "\\n",
        "_ARGCOMPLETE_DFS": "\\t",
        "_ARGCOMPLETE_SUPPRESS_SPACE": "1",
        "_ARGCOMPLETE_SHELL": "fish",
        "_ARGCOMPLETE_STDOUT_FILENAME": handle.name,
        "COMP_LINE": line,
        "COMP_POINT": str(len(line)),
    }
    try:
        try:
            subprocess.run(
                [context.args[0].value],
                env=env,
                timeout=10,
                stdout=subprocess.DEVNULL,
                stderr=subprocess.DEVNULL,
            )
        except (OSError, subprocess.TimeoutExpired):
            # agent6 is an alias/abbrev rather than a binary, or it hung:
            # no candidates, and no exception splashed across the prompt.
            return None
        with open(handle.name, encoding="utf-8") as out:
            output = out.read()
    finally:
        os.unlink(handle.name)
    # argcomplete already filtered by the prefix (COMP_POINT is the true
    # cursor); an empty set falls through to xonsh's own completers (e.g.
    # paths). Values the shell would split are quoted -- on the bare value,
    # so a trailing-sep directory is still detected and keeps no-space
    # completing into itself.
    candidates = set()
    for entry in output.splitlines():
        if not entry.strip():
            continue
        value, _, desc = entry.strip().partition("\\t")
        value = value.strip()
        candidates.add(
            RichCompletion(
                shlex.quote(value),
                description=desc.strip(),
                append_space=not value.endswith(os.sep),
            )
        )
    return candidates


completer.add_one_completer("agent6", _agent6_completer, "start")
"""


def detect_shell() -> str:
    """The interactive shell this command was launched from.

    Walks up the process tree (Linux `/proc`) to the nearest ancestor that
    is a known shell: `$SHELL` is the login shell, not the running one (a
    fish started from bash keeps `$SHELL=bash`), and the direct parent can
    be a wrapper like `uv`. Falls back to `$SHELL`'s basename when the
    walk finds nothing (macOS, no `/proc`)."""
    pid = os.getppid()
    for _ in range(10):
        try:
            comm = (_PROC / str(pid) / "comm").read_text(encoding="utf-8").strip()
            stat = (_PROC / str(pid) / "stat").read_text(encoding="utf-8")
        except OSError:
            break
        if comm in SHELLS:
            return comm
        # stat: "pid (comm) state ppid ..."; comm may contain spaces/parens,
        # so split at the LAST ")". ppid is the second field after it.
        try:
            pid = int(stat.rsplit(")", 1)[1].split()[1])
        except (IndexError, ValueError):
            break
        if pid <= 1:
            break
    return Path(os.environ.get("SHELL", "")).name


def _rc_path(shell: str) -> Path:
    if shell == "bash":
        return Path.home() / ".bashrc"
    # zsh reads .zshrc from $ZDOTDIR when set, else $HOME.
    return Path(os.environ.get("ZDOTDIR") or Path.home()) / ".zshrc"


# Where a shell that auto-loads its completions reads ours, under the config
# home (xonsh sources every file in rc.d on start).
_AUTOLOAD = {
    "fish": ("fish", "completions", "agent6.fish"),
    "xonsh": ("xonsh", "rc.d", "agent6.xsh"),
}


def _autoload_path(shell: str) -> Path:
    xdg = os.environ.get("XDG_CONFIG_HOME")
    base = Path(xdg) if xdg else Path.home() / ".config"
    return base.joinpath(*_AUTOLOAD[shell])


def _install_bash_zsh(shell: str, code: str) -> int:
    script = global_config_dir() / f"completions.{shell}"
    script.parent.mkdir(parents=True, exist_ok=True)
    script.write_text(code, encoding="utf-8")
    rc = _rc_path(shell)
    # The path (from XDG_CONFIG_HOME) lands in shell text the operator's
    # shell later sources; shlex.quote keeps any metacharacter in it inert.
    q = shlex.quote(str(script))
    block = f"\n{_MARK_BEGIN}\n[ -f {q} ] && source {q}  # agent6 tab-completion\n{_MARK_END}\n"
    existing = read_operator_file(rc) if rc.exists() else ""
    if _MARK_BEGIN in existing:
        if (
            existing.count(_MARK_BEGIN) != 1
            or existing.count(_MARK_END) != 1
            or existing.index(_MARK_END) < existing.index(_MARK_BEGIN)
        ):
            # The rc file is the operator's; agent6 edits only its one owned
            # marker block, and a mangled or duplicated one is theirs to fix.
            print(
                f"[agent6] ERROR: {rc} holds malformed agent6 completion markers"
                f" ({_MARK_BEGIN} / {_MARK_END}); fix or remove them and rerun.",
                file=sys.stderr,
            )
            return 2
        start = existing.index(_MARK_BEGIN)
        end = existing.index(_MARK_END) + len(_MARK_END)
        current = existing[start:end]
        wanted = block.strip("\n")
        if current == wanted:
            print(f"[agent6] refreshed {script} (already sourced from {rc})")
        else:
            # A moved config home leaves the block pointing at the old script
            # path; reporting "already sourced" then was a lie.
            rc.write_text(existing[:start] + wanted + existing[end:], encoding="utf-8")
            print(f"[agent6] updated the source path in {rc}")
    else:
        with rc.open("a", encoding="utf-8") as fh:
            fh.write(block)
        print(f"[agent6] wrote {script} and added a source line to {rc}")
    print(f"[agent6] activate now with: source {rc}   (or start a new shell: exec $SHELL)")
    return 0


def _install_autoloaded(code: str, target: Path, shell: str) -> int:
    """fish and xonsh share the auto-load model: write the file, done."""
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(code, encoding="utf-8")
    print(f"[agent6] wrote {target} ({shell} loads it automatically)")
    return 0


def cmd_completions(shell_arg: str | None, *, print_only: bool) -> int:
    shell = shell_arg or detect_shell()
    if shell not in SHELLS:
        detected = f" (detected {shell!r})" if shell else ""
        error(
            f"unsupported or unknown shell{detected}."
            f" Pass one of: agent6 completions {'|'.join(SHELLS)}"
        )
        return 2
    # Xonsh is not an argcomplete backend; it gets a generated completer.
    code = _XONSH_SCRIPT if shell == "xonsh" else shellcode(["agent6"], shell=shell)
    if print_only:
        print(code)
        return 0
    if shell in _AUTOLOAD:
        return _install_autoloaded(code, _autoload_path(shell), shell)
    return _install_bash_zsh(shell, code)
